export const technologyFamilies = [
  { id: "languages", label: "PROGRAMMING LANGUAGES" },
  { id: "web", label: "WEB / FRONTEND" },
  { id: "java-frameworks", label: "JAVA / APPLICATION FRAMEWORKS" },
  { id: "data", label: "DATABASES / DATA" },
  { id: "apis", label: "APIs / MESSAGING" },
  { id: "infrastructure", label: "SERVERS / INFRASTRUCTURE" },
  { id: "build", label: "BUILD / TESTING" },
  { id: "enterprise", label: "ENTERPRISE / SECURITY" },
  { id: "ai", label: "AI / MODERN DATA" },
] as const;

export type TechnologyFamilyId = (typeof technologyFamilies)[number]["id"];

export const technologyFamilyById: Readonly<
  Record<string, TechnologyFamilyId>
> = {
  java: "languages",
  c: "languages",
  cplusplus: "languages",
  basic: "languages",
  "visual-basic": "languages",
  smalltalk: "languages",
  python: "languages",
  html: "web",
  css: "web",
  javascript: "web",
  typescript: "web",
  nodejs: "web",
  react: "web",
  angular: "web",
  jquery: "web",
  "spring-framework": "java-frameworks",
  "spring-boot": "java-frameworks",
  "spring-data": "java-frameworks",
  hibernate: "java-frameworks",
  "spring-webflux-reactor": "java-frameworks",
  sql: "data",
  plsql: "data",
  "oracle-database": "data",
  postgresql: "data",
  "microsoft-sql-server": "data",
  mongodb: "data",
  redis: "data",
  elasticsearch: "data",
  qdrant: "ai",
  "oracle-rac": "data",
  "rest-apis": "apis",
  "soap-web-services": "apis",
  graphql: "apis",
  "apache-kafka": "apis",
  linux: "infrastructure",
  docker: "infrastructure",
  "apache-tomcat": "infrastructure",
  "jboss-wildfly": "infrastructure",
  weblogic: "infrastructure",
  "oracle-application-server": "infrastructure",
  haproxy: "infrastructure",
  maven: "build",
  gradle: "build",
  "oracle-adf": "enterprise",
  liferay: "enterprise",
  pki: "enterprise",
  blockchain: "enterprise",
  birt: "enterprise",
  nexus: "enterprise",
  jdeveloper: "enterprise",
  toad: "enterprise",
  opengl: "enterprise",
  "spring-ai": "ai",
  gemini: "ai",
};
